name: homebrands
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bloc:
  flutter_bloc:
  equatable: ^0.5.1
  carousel_slider:
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  smooth_star_rating: 1.0.3
  flutter_svg: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/products/
    - assets/images/categories/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal-Light.ttf
        - asset: assets/fonts/AirbnbCereal-Book.ttf
        - asset: assets/fonts/AirbnbCereal-Medium.ttf
        - asset: assets/fonts/AirbnbCereal-Bold.ttf
        - asset: assets/fonts/AirbnbCereal-Black.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
